rapid7/awsaml

lib/server.js, views/refresh.jsx
This commit adds AccountId to the values displayed on the refresh
page.  This change makes is a little easier which account you are using;
the Okta metadata url is not very descriptive.
=> Display AccountId on refresh page

views/layouts/default.jsx, views/refresh.jsx
Fixed issue where prism.js's css wasn't actually being loaded. Added functionality to determine which css class to use to render the export/set statement.
=> Bug in export/set statement display

app.js, lib/server.js, package.json, public/css/app.css, views/configure.jsx, views/error.jsx, views/refresh.jsx
Resolves #5. This adds improved error displays and redirection on certain error conditions. 
In the case of a invalid metadata url or invalid SAML metadata, an error will display on the configure page. If an error occurs with manually refreshing the main page, such as if the user's AWS session has timed out, the user will be redirected to their SAML provider. If the user is still logged in, their AWS credentials will be refreshed and they will be redirected back to the main Awsaml screen.
=> Better error handling

package.json
This fixes #11 by packaging Awsaml with version 0.36.7 of Electron. The application no longer throws an uncaught exception when launched.
=> Fix Electron package version

lib/server.js
Fixes #12 where clicking the refresh button after the AWS session had timed out would cause the application to crash.
=> Fix refresh button broken after AWS session timeout

package.json
This bumps the version number to 1.1.0 for the release. It also adds a link to the issue tracker so the `npm bugs` command works.
=> Feature prep v1.1.0 release

package.json, test/.eslintrc.yaml
This fixes #33. The `npm test` command runs [Mocha](https://mochajs.org/) and processes any tests in the "test" folder at the root of the project. An [eslint](http://eslint.org/) configuration is provided for tests so they can use the global Mocha variables and follow [Mocha's recommendation to avoid arrow functions](https://mochajs.org/#arrow-functions). Assertions are provided by the [Should.js](https://shouldjs.github.io/) library.
=> Feature: Mocha test framework

app.js, lib/server.js, public/css/app.css, views/refresh.jsx
This change adds a logout button the `refresh` page and a logout endpoint that does the following:
* Clears the refresh interval
* Clears the session data
* Redirects to the `configureUrl`
I'm not sure how to go about writing tests for this... 
Fixes #48
=> Add logout button to refresh page

app.js, package.json
This fixes #52. [electron-packager](https://www.npmjs.com/package/electron-packager) has been upgraded to version 7.0.1 and [electron-prebuilt](https://www.npmjs.com/package/electron-prebuilt) has been upgraded to version 0.37.8.
=> Fix: Upgrade Electron packaging

CHANGELOG.md, package.json
This bumps the version number to 1.2.0 for the release.
=> Feature prep v1.2.0 release

lib/response.js, lib/routes/auth.js, lib/routes/configure.js, lib/routes/logout.js, lib/routes/refresh.js, lib/server-config.js, lib/server.js
This PR is the next step in addressing #23. It refactors routes out of the monolithic `lib/server.js` into their own routes. It also moves the responsibility for server configuration into its own module.
This gives us a foundation for further refactoring these routes into RESTful ones that serve JSON rather than a `react-view`.
=> Refactor routes

app.js, lib/routes/logout.js, lib/server.js
This fixes #60.
The automatic token renewal process now runs, even if you log out and log back in.
=> Fix: Renew fails after logout

.gitignore, lib/aws-credentials.js, test/.eslintrc.yaml, test/aws-credentials.js
This closes #34 by adding tests around the `AwsCredentials` class. Additionally, it fixes a bug where Awsaml would crash when trying to save AWS credentials if the `$HOME` path wasn't set.
=> Feature: AwsCredentials tests

README.md, brew/cask/awsaml.rb
Add a brew-cask file for awsaml, currently pinned to the 1.2.0 release.
The cask file passes audit and style checks, so it might even be submitted to the main brew repo if you'd like.
=> Add brew cask file

lib/storage.js
This prevents parsing a storage file that is empty (which ends up
throwing a SyntaxError).
cc @emcanearney-r7 who initially found #71.
=> Fix #71 - Set data to an empty object if the storage file is empty

views/refresh.jsx
The original issue copied from #66:
> Not that this is a very likely attack vector, but with that window up, someone could capture the information in that window (with a camera? a really good memory?) and then transfer it to another device and use AWS services impersonating me.
>
> Since awsml conveniently writes that data to ~/.aws/credentials already, it also seems unlikely that anyone would really need to copy and paste it from the awsaml GUI to somewhere else.
We now collapse the access key, secret key, and session token fields by default. The account ID field remains opened by default.
=> Fix #66 - hide sensitive information by default

CHANGELOG.md, package.json
The bumps the version to 1.3.0 and adds notes to the CHANGELOG so we can cut a new release.
=> Feature: Prep v1.3.0 release

README.md, brew/cask/awsaml.rb
This updates the Homebrew cask file so it points at the latest v1.3.0 release. It also links to Homebrew in the README so people know where they can get it.
=> Fix: Update Homebrew for v1.3.0

CHANGELOG.md, package.json
* Update release notes for v1.4.0
* Bump version in package.json to 1.4.0.
=> Prepare for the v1.4.0 release

public/css/app.css, views/configure.jsx
@dgreene-r7  / @erran-r7 
This adds a button to the historic links allowing you to directly login to a previously accessed environment.
I am not sure how to make it cleaner, so this is just to start a discussion.
=> Add a login button to the right hand side

package.json, yarn.lock
This fixes #92. I'm explicitly pinning the Electron version in the dependencies section of package.json to 1.6.8 and removing the `--version` flag from the build script. So electron-packager will use the version of Electron it finds in package.json, and we only have one place to change the version number when we want to upgrade Electron.
=> Fix: Pin Electron version to 1.6.11

lib/routes/configure.js, lib/routes/refresh.js, public/css/app.css, views/configure.jsx
This allows the user to edit the profileName directly from the ui. This removes the text and replaces it with a input field instead. 
I couldn't get it working with editable text which may be nice instead
=> OPS-1 make profileName user configurable

CHANGELOG.md, package.json
The bumps the version to 1.5.0 and adds notes to the CHANGELOG so we can cut a new release.
=> Feature: Prep v1.5.0 release

brew/cask/awsaml.rb
This updates the `brew/cask/awsaml.rb` file so it installs [v1.5.0](https://github.com/rapid7/awsaml/releases/tag/v1.5.0). Additionally, it removes the `license` stanza as that's no longer supported. Casks with a `license` stanza generate the following error:
```
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
```
=> Fix: Update Homebrew cask for v1.5.0

README.md, package.json, yarn.lock
This updates the `body-parser`, `electron`, `electron-packager`, `errorhandler`, `mkdirp`, and `passport-saml` packages to their latest versions so we pick up security patches.
I haven't updated the React and Babel related packages, yet. There's a lot of interaction between them, and I want to get the version dependencies right so everything works. That will come as a separate pull request.
I also updated the README to reflect the version of Node that's pinned in the `.nvmrc` file and to indicate that we're now using Yarn for building.
=> Fix: Pick up security patches

package.json
This fixes #101 by using symlinks in the zip packge (the "-y" flag) instead of keeping multiple copies of the same file. On macOS this means the Awsaml.app folder can be signed and then zipped without invalidating the signature. It also makes the macOS zip file about 2x smaller.
Testing showed no changes in the Linux zip when building on both macOS and Linux.
=> Fix: Use symlinks in zip packages

README.md, app.js
By default, credentials last an hour.  Previously, awsaml would refresh
the credentials every hour minus ten seconds.  This leaves the potential
of a long-running command picking up those credentials right before they
expire, and them expiring partway through running the command, and the
command failing.  Terraform is one such example.
This change will refresh the credentials every half hour.  This *should*
guarantee that whenever a command is run, it has at least a half hour of
useful life on the credential that it picks up from the credentials
file.
A bug still exists:  The timer starts from the time awsaml launches, not
from the time a user logs in.  This is okay, because it should still
guarantee more frequent updates than necessary to retain valid and
recent credentials.
=> Refresh credentials every half-duration

CHANGELOG.md, package.json
The bumps the version to 1.6.0 and adds notes to the CHANGELOG so we can cut a new release.
=> Feature: Prep v1.6.0 release

CHANGELOG.md, package.json
This bumps the version to 1.6.1 and adds notes to the CHANGELOG so we can cut a new release.
=> Feature: Prep v1.6.1 release

brew/cask/awsaml.rb
```
$ shasum -a 256 awsaml-v1.6.1-darwin-x64.zip
8840a68b2e1c2ce1fa46a3bb830dd1d2d997e1e7cd49fdc7bcfec40351df97e4  awsaml-v1.6.1-darwin-x64.zip
$ brew cask _appcast_checkpoint --calculate 'https://github.com/rapid7/awsaml/releases.atom'
61fe9e234a69897a47af09aed4c0478e03a1c4e4c874174555db033a14aedea2
```
=> Fix: Update Homebrew cask for v1.6.1

.gitignore, app-menu.js, app.js
Added workaround for the SAML exception error where sometimes the client gets into a SAML error state and doesn't work anymore. This adds a new option 'Reset' to the View menu which brings you back to the initial login/configuration page.
=> Added workaround for the SAML exception error

brew/cask/awsaml.rb
This updates the `brew/cask/awsaml.rb` file so it installs [v2.0.0](https://github.com/rapid7/awsaml/releases/tag/v2.0.0).
=> Fix update homebrew cask for v2.0.0

api/routes/configure.js, api/routes/profile.js, package.json, src/containers/configure/Configure.js, src/containers/configure/Login.js, src/containers/configure/RecentLogins.js, src/index.js, yarn.lock
This adds a very rudimentary search function for recent logins.  It's a simple case insenstive search.  It doesn't re-order results or anything fancy like that.  This should make it easier to quickly find accounts if you have given them helpful aliases.
Currently it searches both the name and url.  Searching the URL may not make sense, but it didn't hurt in my tests.
GH-118
=> Add basic account filter/search

README.md, api/routes/auth.js, api/routes/configure.js, api/routes/refresh.js, api/routes/select-role.js, api/server.js, package.json, src/actions/select-role.js, src/apis/index.js, src/constants/index.js, src/containers/App.js, src/containers/components/InputGroupWithCopyButton.js, src/containers/configure/Configure.js, src/containers/configure/Login.js, src/containers/configure/RecentLogins.js, src/containers/refresh/Credentials.js, src/containers/refresh/Refresh.js, src/containers/select-role/Role.js, src/containers/select-role/SelectRole.js, src/reducers/index.js, src/reducers/select-role.js
This adds a role switcher when multiple roles are passed via the SAML assertion.  This is similar to how the AWS console handles multiple roles.  When a single role is passed, the behavior is unchanged.
This also includes a few random fixes/improvements that I found along the way:
- A copy button for the terminal copy/pasta text
- Display credential data as a grid
- Fix the bugs and URLs when running in react developer mode
**Note to reviewers:**
I am not a react or express developer, much less a react+redux+express+electron developer.  Please keep this in mind when reviewing and feel free to suggest stylistic changes.
**Note to Okta users:**
AWS requires that multiple roles are passed as multiple values to the `https://aws.amazon.com/SAML/Attributes/Role` attribute (see [the AWS …
=> Add multiple role support

CHANGELOG.md, brew/cask/awsaml.rb
This updates the brew/cask/awsaml.rb file so it installs v2.1.0.
=> Fix: Update homebrew cask for v2.1.0

electron/electron.js
There's absolutely no reason that hardware acceleration should be enabled by default and on a Mac laptop it will pin the GPU to discrete graphics mode which eats up battery life.
=> Disable hardware acceleration

api/routes/configure.js, src/containers/components/ComponentWithError.js, src/containers/configure/Configure.js, src/containers/configure/ConfigureMetadata.js
Allow users to name connections on first connection.
Currently to name an account connections users must login and get the connection added to the `Recent Logins` list, only then can the user edit the historically saved connection.  This PR adds an `Account Alias` optional field to the top level connection form that, if filed in, will be use to name the connection in the `Recent Logins`.
=> Name connections

brew/cask/awsaml.rb
Updates cask to version 2.2.0, bringing in some important changes.
NOTE: we are removing the appcast checkpoint
SEE: https://github.com/Homebrew/homebrew-cask/issues/48051
=> Update cask to 2.2.0

README.md
Updated instructions for installing Awsaml. Previous installation step with homebrew for MacOS is no longer supported and requires an extra step.
=> Update README.md for Awsaml installation steps for MacOS

api/routes/refresh.js
Need to set the aws region to "us-gov-west-1" if it is trying to assume a role in govcloud as otherwise it uses us-east-1 by default which will not work in a govcloud account
=> Update to allow awsaml to work with govcloud

api/aws-credentials.js, api/routes/refresh.js
Update Awsaml to add region=us-gov-west-1 in .aws/credentials when signing into a govcloud account
This is useful because the aws cli defaults region to us-east-1 which will fail when logged into a govcloud account i.e. you would need to do 'aws s3 ls --region us-gov-west-1' 
Built a local version of awsaml, signed into multiple consumer accounts, then a govcloud account. Then I looked inside .aws/credentials checked that the region has only been set up for govcloud accounts and commercial had been left untouched
=> Adding region = us-gov-west-1 when logged onto a govcloud account

api/routes/refresh.js
When using with FedRamp and commercial accounts, swapping between types had issues because the region was incorrect.
Ran testing here with combined branches:
https://github.com/rapid7/awsaml/actions/runs/1993263022
=> Patching fedramp usage

package.json, yarn.lock
This updates the `electron-packager` version to allow building a windows installer for awsaml.  Before this, several errors were present for windows builds on mac.
=> Updating electron-packager to build windows installer

src/containers/configure/Login.js
This PR adds a confirmation dialog when deleting a login entry. This is in response to issue #204 by @ceastman-r7 requesting this feature be added.
The changes have been tested on macOS and Windows.
=> add confirmation when deleting profile

.github/workflows/node.js.yml, forge.config.js
This PR fixes an issue where the `includeFiles` array will be evaluated when forge imports the config so in the event that the `build` directory is empty or doesn't exist the UI assets won't be bundled into the `app.asar`. The change adds the contents of the `build` directory at the end of the `generateAssets` hook so we know it will exist.
=> Fixed issue where ui assets wouldn't be properly packaged

src/renderer/containers/refresh/Credentials.js
In dark mode the keys within the credentials flyout aren't dark mode-aware. In dark mode they display like this:
They display correctly in light mode. This PR adds conditional styling to those keys to ensure they're colored correctly.
=> Make credential keys dark mode-aware.

package.json, src/main/index.js, yarn.lock
This PR implements some basic logging in the Main process.
By default, logs are written to the following locations:
> on Linux: ~/.config/Awsaml/logs/main.log
> on macOS: ~/Library/Logs/Awsaml/main.log
> on Windows: %USERPROFILE%\AppData\Roaming\Awsaml\logs\main.log
=> Add basic logging

README.md, brew/cask/awsaml.rb
It looks like [the Jenkins job](https://github.com/rapid7/awsaml/commit/ad48e4b2f9e02a3b1b8e086db151173e7c65682a) which is updating the version number in the `brew/cask/awsaml.rb` file isn't also updating the `sha256` line. 
<details>
</details>
<details>
</details>
I didn't open an Issue in this repo because I suspect there is a separate repo for the Jenkins job which is doing this work which will need updating. LMK if you want a ticket in the internal ticket tracking system for it.
=> Cask shasum mismatch for 3.1.2

.eslintrc.js
Without this, on Windows, running `yarn run react-build` errors with `Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`
=> Windows-friendly eslint linebreak config

brew/cask/awsaml.rb, package.json
This PR reverts the automated version bump that occurred whilst working on a release package. The draft release has been postponed.
=> Revert version bump from draft release

brew/cask/awsaml.rb
See title. We'll bump to 3.2.0 once we fix the build issues.
=> Revert cask installer to 3.1.2
